<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Municipios de Venezuela organizados por estado
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            // ========== AMAZONAS (state_id: 1) - 7 municipios ==========
            ['id' => '1', 'name' => 'Alto Orinoco', 'state_id' => '1'],
            ['id' => '2', 'name' => 'Atabapo', 'state_id' => '1'],
            ['id' => '3', 'name' => 'Atures', 'state_id' => '1'],
            ['id' => '4', 'name' => 'Autana', 'state_id' => '1'],
            ['id' => '5', 'name' => 'Manapiare', 'state_id' => '1'],
            ['id' => '6', 'name' => 'Maroa', 'state_id' => '1'],
            ['id' => '7', 'name' => 'Río Negro', 'state_id' => '1'],

            // ========== ANZOÁTEGUI (state_id: 2) - 21 municipios ==========
            ['id' => '8', 'name' => 'Anaco', 'state_id' => '2'],
            ['id' => '9', 'name' => 'Aragua', 'state_id' => '2'],
            ['id' => '10', 'name' => 'Diego Bautista Urbaneja', 'state_id' => '2'],
            ['id' => '11', 'name' => 'Fernando Peñalver', 'state_id' => '2'],
            ['id' => '12', 'name' => 'Francisco del Carmen Carvajal', 'state_id' => '2'],
            ['id' => '13', 'name' => 'Francisco de Miranda', 'state_id' => '2'],
            ['id' => '14', 'name' => 'Guanta', 'state_id' => '2'],
            ['id' => '15', 'name' => 'Independencia', 'state_id' => '2'],
            ['id' => '16', 'name' => 'José Gregorio Monagas', 'state_id' => '2'],
            ['id' => '17', 'name' => 'Juan Antonio Sotillo', 'state_id' => '2'],
            ['id' => '18', 'name' => 'Juan Manuel Cajigal', 'state_id' => '2'],
            ['id' => '19', 'name' => 'Libertad', 'state_id' => '2'],
            ['id' => '20', 'name' => 'Manuel Ezequiel Bruzual', 'state_id' => '2'],
            ['id' => '21', 'name' => 'Pedro María Freites', 'state_id' => '2'],
            ['id' => '22', 'name' => 'Píritu', 'state_id' => '2'],
            ['id' => '23', 'name' => 'San José de Guanipa', 'state_id' => '2'],
            ['id' => '24', 'name' => 'San Juan de Capistrano', 'state_id' => '2'],
            ['id' => '25', 'name' => 'Santa Ana', 'state_id' => '2'],
            ['id' => '26', 'name' => 'Simón Bolívar', 'state_id' => '2'],
            ['id' => '27', 'name' => 'Simón Rodríguez', 'state_id' => '2'],
            ['id' => '28', 'name' => 'Sir Arthur McGregor', 'state_id' => '2'],

            // ========== APURE (state_id: 3) - 7 municipios ==========
            ['id' => '29', 'name' => 'Achaguas', 'state_id' => '3'],
            ['id' => '30', 'name' => 'Biruaca', 'state_id' => '3'],
            ['id' => '31', 'name' => 'Muñoz', 'state_id' => '3'],
            ['id' => '32', 'name' => 'Páez', 'state_id' => '3'],
            ['id' => '33', 'name' => 'Pedro Camejo', 'state_id' => '3'],
            ['id' => '34', 'name' => 'Rómulo Gallegos', 'state_id' => '3'],
            ['id' => '35', 'name' => 'San Fernando', 'state_id' => '3'],

            // ========== ARAGUA (state_id: 4) - 18 municipios ==========
            ['id' => '36', 'name' => 'Bolívar', 'state_id' => '4'],
            ['id' => '37', 'name' => 'Camatagua', 'state_id' => '4'],
            ['id' => '38', 'name' => 'Francisco Linares Alcántara', 'state_id' => '4'],
            ['id' => '39', 'name' => 'Girardot', 'state_id' => '4'],
            ['id' => '40', 'name' => 'José Ángel Lamas', 'state_id' => '4'],
            ['id' => '41', 'name' => 'José Félix Ribas', 'state_id' => '4'],
            ['id' => '42', 'name' => 'José Rafael Revenga', 'state_id' => '4'],
            ['id' => '43', 'name' => 'Libertador', 'state_id' => '4'],
            ['id' => '44', 'name' => 'Mario Briceño Iragorry', 'state_id' => '4'],
            ['id' => '45', 'name' => 'Ocumare de la Costa de Oro', 'state_id' => '4'],
            ['id' => '46', 'name' => 'San Casimiro', 'state_id' => '4'],
            ['id' => '47', 'name' => 'San Sebastián', 'state_id' => '4'],
            ['id' => '48', 'name' => 'Santiago Mariño', 'state_id' => '4'],
            ['id' => '49', 'name' => 'Santos Michelena', 'state_id' => '4'],
            ['id' => '50', 'name' => 'Sucre', 'state_id' => '4'],
            ['id' => '51', 'name' => 'Tovar', 'state_id' => '4'],
            ['id' => '52', 'name' => 'Urdaneta', 'state_id' => '4'],
            ['id' => '53', 'name' => 'Zamora', 'state_id' => '4'],

            // ========== BARINAS (state_id: 5) - 12 municipios ==========
            ['id' => '54', 'name' => 'Alberto Arvelo Torrealba', 'state_id' => '5'],
            ['id' => '55', 'name' => 'Andrés Eloy Blanco', 'state_id' => '5'],
            ['id' => '56', 'name' => 'Antonio José de Sucre', 'state_id' => '5'],
            ['id' => '57', 'name' => 'Arismendi', 'state_id' => '5'],
            ['id' => '58', 'name' => 'Barinas', 'state_id' => '5'],
            ['id' => '59', 'name' => 'Bolívar', 'state_id' => '5'],
            ['id' => '60', 'name' => 'Cruz Paredes', 'state_id' => '5'],
            ['id' => '61', 'name' => 'Ezequiel Zamora', 'state_id' => '5'],
            ['id' => '62', 'name' => 'Obispos', 'state_id' => '5'],
            ['id' => '63', 'name' => 'Pedraza', 'state_id' => '5'],
            ['id' => '64', 'name' => 'Rojas', 'state_id' => '5'],
            ['id' => '65', 'name' => 'Sosa', 'state_id' => '5'],

            // ========== BOLÍVAR (state_id: 6) - 11 municipios ==========
            ['id' => '66', 'name' => 'Caroní', 'state_id' => '6'],
            ['id' => '67', 'name' => 'Cedeño', 'state_id' => '6'],
            ['id' => '68', 'name' => 'El Callao', 'state_id' => '6'],
            ['id' => '69', 'name' => 'Gran Sabana', 'state_id' => '6'],
            ['id' => '70', 'name' => 'Heres', 'state_id' => '6'],
            ['id' => '71', 'name' => 'Piar', 'state_id' => '6'],
            ['id' => '72', 'name' => 'Raúl Leoni', 'state_id' => '6'],
            ['id' => '73', 'name' => 'Roscio', 'state_id' => '6'],
            ['id' => '74', 'name' => 'Sifontes', 'state_id' => '6'],
            ['id' => '75', 'name' => 'Sucre', 'state_id' => '6'],
            ['id' => '76', 'name' => 'Padre Pedro Chien', 'state_id' => '6'],

            // ========== CARABOBO (state_id: 7) - 14 municipios ==========
            ['id' => '77', 'name' => 'Bejuma', 'state_id' => '7'],
            ['id' => '78', 'name' => 'Carlos Arvelo', 'state_id' => '7'],
            ['id' => '79', 'name' => 'Diego Ibarra', 'state_id' => '7'],
            ['id' => '80', 'name' => 'Guacara', 'state_id' => '7'],
            ['id' => '81', 'name' => 'Juan José Mora', 'state_id' => '7'],
            ['id' => '82', 'name' => 'Libertador', 'state_id' => '7'],
            ['id' => '83', 'name' => 'Los Guayos', 'state_id' => '7'],
            ['id' => '84', 'name' => 'Miranda', 'state_id' => '7'],
            ['id' => '85', 'name' => 'Montalbán', 'state_id' => '7'],
            ['id' => '86', 'name' => 'Naguanagua', 'state_id' => '7'],
            ['id' => '87', 'name' => 'Puerto Cabello', 'state_id' => '7'],
            ['id' => '88', 'name' => 'San Diego', 'state_id' => '7'],
            ['id' => '89', 'name' => 'San Joaquín', 'state_id' => '7'],
            ['id' => '90', 'name' => 'Valencia', 'state_id' => '7'],

            // ========== COJEDES (state_id: 8) - 9 municipios ==========
            ['id' => '91', 'name' => 'Anzoátegui', 'state_id' => '8'],
            ['id' => '92', 'name' => 'Tinaquillo', 'state_id' => '8'],
            ['id' => '93', 'name' => 'Girardot', 'state_id' => '8'],
            ['id' => '94', 'name' => 'Lima Blanco', 'state_id' => '8'],
            ['id' => '95', 'name' => 'Pao de San Juan Bautista', 'state_id' => '8'],
            ['id' => '96', 'name' => 'Ricaurte', 'state_id' => '8'],
            ['id' => '97', 'name' => 'Rómulo Gallegos', 'state_id' => '8'],
            ['id' => '98', 'name' => 'San Carlos', 'state_id' => '8'],
            ['id' => '99', 'name' => 'Tinaco', 'state_id' => '8'],

            // ========== DELTA AMACURO (state_id: 9) - 4 municipios ==========
            ['id' => '100', 'name' => 'Antonio Díaz', 'state_id' => '9'],
            ['id' => '101', 'name' => 'Casacoima', 'state_id' => '9'],
            ['id' => '102', 'name' => 'Pedernales', 'state_id' => '9'],
            ['id' => '103', 'name' => 'Tucupita', 'state_id' => '9'],

            // ========== DISTRITO CAPITAL (state_id: 10) - 1 municipio ==========
            ['id' => '104', 'name' => 'Libertador', 'state_id' => '10'],

            // ========== FALCÓN (state_id: 11) - 25 municipios ==========
            ['id' => '105', 'name' => 'Acosta', 'state_id' => '11'],
            ['id' => '106', 'name' => 'Bolívar', 'state_id' => '11'],
            ['id' => '107', 'name' => 'Buchivacoa', 'state_id' => '11'],
            ['id' => '108', 'name' => 'Cacique Manaure', 'state_id' => '11'],
            ['id' => '109', 'name' => 'Carirubana', 'state_id' => '11'],
            ['id' => '110', 'name' => 'Colina', 'state_id' => '11'],
            ['id' => '111', 'name' => 'Dabajuro', 'state_id' => '11'],
            ['id' => '112', 'name' => 'Democracia', 'state_id' => '11'],
            ['id' => '113', 'name' => 'Falcón', 'state_id' => '11'],
            ['id' => '114', 'name' => 'Federación', 'state_id' => '11'],
            ['id' => '115', 'name' => 'Jacura', 'state_id' => '11'],
            ['id' => '116', 'name' => 'José Laurencio Silva', 'state_id' => '11'],
            ['id' => '117', 'name' => 'Los Taques', 'state_id' => '11'],
            ['id' => '118', 'name' => 'Mauroa', 'state_id' => '11'],
            ['id' => '119', 'name' => 'Miranda', 'state_id' => '11'],
            ['id' => '120', 'name' => 'Monseñor Iturriza', 'state_id' => '11'],
            ['id' => '121', 'name' => 'Palmasola', 'state_id' => '11'],
            ['id' => '122', 'name' => 'Petit', 'state_id' => '11'],
            ['id' => '123', 'name' => 'Píritu', 'state_id' => '11'],
            ['id' => '124', 'name' => 'San Francisco', 'state_id' => '11'],
            ['id' => '125', 'name' => 'Sucre', 'state_id' => '11'],
            ['id' => '126', 'name' => 'Tocópero', 'state_id' => '11'],
            ['id' => '127', 'name' => 'Unión', 'state_id' => '11'],
            ['id' => '128', 'name' => 'Urumaco', 'state_id' => '11'],
            ['id' => '129', 'name' => 'Zamora', 'state_id' => '11'],

            // ========== GUÁRICO (state_id: 12) - 15 municipios ==========
            ['id' => '130', 'name' => 'Camaguán', 'state_id' => '12'],
            ['id' => '131', 'name' => 'Chaguaramas', 'state_id' => '12'],
            ['id' => '132', 'name' => 'El Socorro', 'state_id' => '12'],
            ['id' => '133', 'name' => 'José Félix Ribas', 'state_id' => '12'],
            ['id' => '134', 'name' => 'José Tadeo Monagas', 'state_id' => '12'],
            ['id' => '135', 'name' => 'Juan Germán Roscio', 'state_id' => '12'],
            ['id' => '136', 'name' => 'Julián Mellado', 'state_id' => '12'],
            ['id' => '137', 'name' => 'Las Mercedes', 'state_id' => '12'],
            ['id' => '138', 'name' => 'Leonardo Infante', 'state_id' => '12'],
            ['id' => '139', 'name' => 'Ortiz', 'state_id' => '12'],
            ['id' => '140', 'name' => 'Pedro Zaraza', 'state_id' => '12'],
            ['id' => '141', 'name' => 'San Gerónimo de Guayabal', 'state_id' => '12'],
            ['id' => '142', 'name' => 'San José de Guaribe', 'state_id' => '12'],
            ['id' => '143', 'name' => 'Santa María de Ipire', 'state_id' => '12'],
            ['id' => '144', 'name' => 'Sebastián Francisco de Miranda', 'state_id' => '12'],

            // ========== LARA (state_id: 13) - 9 municipios ==========
            ['id' => '145', 'name' => 'Andrés Eloy Blanco', 'state_id' => '13'],
            ['id' => '146', 'name' => 'Crespo', 'state_id' => '13'],
            ['id' => '147', 'name' => 'Iribarren', 'state_id' => '13'],
            ['id' => '148', 'name' => 'Jiménez', 'state_id' => '13'],
            ['id' => '149', 'name' => 'Morán', 'state_id' => '13'],
            ['id' => '150', 'name' => 'Palavecino', 'state_id' => '13'],
            ['id' => '151', 'name' => 'Simón Planas', 'state_id' => '13'],
            ['id' => '152', 'name' => 'Torres', 'state_id' => '13'],
            ['id' => '153', 'name' => 'Urdaneta', 'state_id' => '13'],

            // ========== MÉRIDA (state_id: 14) - 23 municipios ==========
            ['id' => '154', 'name' => 'Alberto Adriani', 'state_id' => '14'],
            ['id' => '155', 'name' => 'Andrés Bello', 'state_id' => '14'],
            ['id' => '156', 'name' => 'Antonio Pinto Salinas', 'state_id' => '14'],
            ['id' => '157', 'name' => 'Aricagua', 'state_id' => '14'],
            ['id' => '158', 'name' => 'Arzobispo Chacón', 'state_id' => '14'],
            ['id' => '159', 'name' => 'Campo Elías', 'state_id' => '14'],
            ['id' => '160', 'name' => 'Caracciolo Parra Olmedo', 'state_id' => '14'],
            ['id' => '161', 'name' => 'Cardenal Quintero', 'state_id' => '14'],
            ['id' => '162', 'name' => 'Guaraque', 'state_id' => '14'],
            ['id' => '163', 'name' => 'Julio César Salas', 'state_id' => '14'],
            ['id' => '164', 'name' => 'Justo Briceño', 'state_id' => '14'],
            ['id' => '165', 'name' => 'Libertador', 'state_id' => '14'],
            ['id' => '166', 'name' => 'Miranda', 'state_id' => '14'],
            ['id' => '167', 'name' => 'Obispo Ramos de Lora', 'state_id' => '14'],
            ['id' => '168', 'name' => 'Padre Noguera', 'state_id' => '14'],
            ['id' => '169', 'name' => 'Pueblo Llano', 'state_id' => '14'],
            ['id' => '170', 'name' => 'Rangel', 'state_id' => '14'],
            ['id' => '171', 'name' => 'Rivas Dávila', 'state_id' => '14'],
            ['id' => '172', 'name' => 'Santos Marquina', 'state_id' => '14'],
            ['id' => '173', 'name' => 'Sucre', 'state_id' => '14'],
            ['id' => '174', 'name' => 'Tovar', 'state_id' => '14'],
            ['id' => '175', 'name' => 'Tulio Febres Cordero', 'state_id' => '14'],
            ['id' => '176', 'name' => 'Zea', 'state_id' => '14'],

            // ========== MIRANDA (state_id: 15) - 21 municipios ==========
            ['id' => '177', 'name' => 'Acevedo', 'state_id' => '15'],
            ['id' => '178', 'name' => 'Andrés Bello', 'state_id' => '15'],
            ['id' => '179', 'name' => 'Baruta', 'state_id' => '15'],
            ['id' => '180', 'name' => 'Brión', 'state_id' => '15'],
            ['id' => '181', 'name' => 'Buroz', 'state_id' => '15'],
            ['id' => '182', 'name' => 'Carrizal', 'state_id' => '15'],
            ['id' => '183', 'name' => 'Chacao', 'state_id' => '15'],
            ['id' => '184', 'name' => 'Cristóbal Rojas', 'state_id' => '15'],
            ['id' => '185', 'name' => 'El Hatillo', 'state_id' => '15'],
            ['id' => '186', 'name' => 'Guaicaipuro', 'state_id' => '15'],
            ['id' => '187', 'name' => 'Independencia', 'state_id' => '15'],
            ['id' => '188', 'name' => 'Lander', 'state_id' => '15'],
            ['id' => '189', 'name' => 'Los Salias', 'state_id' => '15'],
            ['id' => '190', 'name' => 'Páez', 'state_id' => '15'],
            ['id' => '191', 'name' => 'Paz Castillo', 'state_id' => '15'],
            ['id' => '192', 'name' => 'Pedro Gual', 'state_id' => '15'],
            ['id' => '193', 'name' => 'Plaza', 'state_id' => '15'],
            ['id' => '194', 'name' => 'Simón Bolívar', 'state_id' => '15'],
            ['id' => '195', 'name' => 'Sucre', 'state_id' => '15'],
            ['id' => '196', 'name' => 'Urdaneta', 'state_id' => '15'],
            ['id' => '197', 'name' => 'Zamora', 'state_id' => '15'],

            // ========== MONAGAS (state_id: 16) - 13 municipios ==========
            ['id' => '198', 'name' => 'Acosta', 'state_id' => '16'],
            ['id' => '199', 'name' => 'Aguasay', 'state_id' => '16'],
            ['id' => '200', 'name' => 'Bolívar', 'state_id' => '16'],
            ['id' => '201', 'name' => 'Caripe', 'state_id' => '16'],
            ['id' => '202', 'name' => 'Cedeño', 'state_id' => '16'],
            ['id' => '203', 'name' => 'Ezequiel Zamora', 'state_id' => '16'],
            ['id' => '204', 'name' => 'Libertador', 'state_id' => '16'],
            ['id' => '205', 'name' => 'Maturín', 'state_id' => '16'],
            ['id' => '206', 'name' => 'Piar', 'state_id' => '16'],
            ['id' => '207', 'name' => 'Punceres', 'state_id' => '16'],
            ['id' => '208', 'name' => 'Santa Bárbara', 'state_id' => '16'],
            ['id' => '209', 'name' => 'Sotillo', 'state_id' => '16'],
            ['id' => '210', 'name' => 'Uracoa', 'state_id' => '16'],

            // ========== NUEVA ESPARTA (state_id: 17) - 11 municipios ==========
            ['id' => '211', 'name' => 'Antolín del Campo', 'state_id' => '17'],
            ['id' => '212', 'name' => 'Arismendi', 'state_id' => '17'],
            ['id' => '213', 'name' => 'Díaz', 'state_id' => '17'],
            ['id' => '214', 'name' => 'García', 'state_id' => '17'],
            ['id' => '215', 'name' => 'Gómez', 'state_id' => '17'],
            ['id' => '216', 'name' => 'Maneiro', 'state_id' => '17'],
            ['id' => '217', 'name' => 'Marcano', 'state_id' => '17'],
            ['id' => '218', 'name' => 'Mariño', 'state_id' => '17'],
            ['id' => '219', 'name' => 'Península de Macanao', 'state_id' => '17'],
            ['id' => '220', 'name' => 'Tubores', 'state_id' => '17'],
            ['id' => '221', 'name' => 'Villalba', 'state_id' => '17'],

            // ========== PORTUGUESA (state_id: 18) - 14 municipios ==========
            ['id' => '222', 'name' => 'Agua Blanca', 'state_id' => '18'],
            ['id' => '223', 'name' => 'Araure', 'state_id' => '18'],
            ['id' => '224', 'name' => 'Esteller', 'state_id' => '18'],
            ['id' => '225', 'name' => 'Guanare', 'state_id' => '18'],
            ['id' => '226', 'name' => 'Guanarito', 'state_id' => '18'],
            ['id' => '227', 'name' => 'José Vicente de Unda', 'state_id' => '18'],
            ['id' => '228', 'name' => 'Ospino', 'state_id' => '18'],
            ['id' => '229', 'name' => 'Páez', 'state_id' => '18'],
            ['id' => '230', 'name' => 'Papelón', 'state_id' => '18'],
            ['id' => '231', 'name' => 'San Genaro de Boconoíto', 'state_id' => '18'],
            ['id' => '232', 'name' => 'San Rafael de Onoto', 'state_id' => '18'],
            ['id' => '233', 'name' => 'Santa Rosalía', 'state_id' => '18'],
            ['id' => '234', 'name' => 'Sucre', 'state_id' => '18'],
            ['id' => '235', 'name' => 'Turén', 'state_id' => '18'],

            // ========== SUCRE (state_id: 19) - 15 municipios ==========
            ['id' => '236', 'name' => 'Andrés Eloy Blanco', 'state_id' => '19'],
            ['id' => '237', 'name' => 'Andrés Mata', 'state_id' => '19'],
            ['id' => '238', 'name' => 'Arismendi', 'state_id' => '19'],
            ['id' => '239', 'name' => 'Benítez', 'state_id' => '19'],
            ['id' => '240', 'name' => 'Bermúdez', 'state_id' => '19'],
            ['id' => '241', 'name' => 'Bolívar', 'state_id' => '19'],
            ['id' => '242', 'name' => 'Cajigal', 'state_id' => '19'],
            ['id' => '243', 'name' => 'Cruz Salmerón Acosta', 'state_id' => '19'],
            ['id' => '244', 'name' => 'Libertador', 'state_id' => '19'],
            ['id' => '245', 'name' => 'Mariño', 'state_id' => '19'],
            ['id' => '246', 'name' => 'Mejía', 'state_id' => '19'],
            ['id' => '247', 'name' => 'Montes', 'state_id' => '19'],
            ['id' => '248', 'name' => 'Ribero', 'state_id' => '19'],
            ['id' => '249', 'name' => 'Sucre', 'state_id' => '19'],
            ['id' => '250', 'name' => 'Valdez', 'state_id' => '19'],

            // ========== TÁCHIRA (state_id: 20) - 29 municipios ==========
            ['id' => '251', 'name' => 'Andrés Bello', 'state_id' => '20'],
            ['id' => '252', 'name' => 'Antonio Rómulo Costa', 'state_id' => '20'],
            ['id' => '253', 'name' => 'Ayacucho', 'state_id' => '20'],
            ['id' => '254', 'name' => 'Bolívar', 'state_id' => '20'],
            ['id' => '255', 'name' => 'Cárdenas', 'state_id' => '20'],
            ['id' => '256', 'name' => 'Córdoba', 'state_id' => '20'],
            ['id' => '257', 'name' => 'Fernández Feo', 'state_id' => '20'],
            ['id' => '258', 'name' => 'Francisco de Miranda', 'state_id' => '20'],
            ['id' => '259', 'name' => 'García de Hevia', 'state_id' => '20'],
            ['id' => '260', 'name' => 'Guásimos', 'state_id' => '20'],
            ['id' => '261', 'name' => 'Independencia', 'state_id' => '20'],
            ['id' => '262', 'name' => 'Jáuregui', 'state_id' => '20'],
            ['id' => '263', 'name' => 'José María Vargas', 'state_id' => '20'],
            ['id' => '264', 'name' => 'Junín', 'state_id' => '20'],
            ['id' => '265', 'name' => 'Libertad', 'state_id' => '20'],
            ['id' => '266', 'name' => 'Libertador', 'state_id' => '20'],
            ['id' => '267', 'name' => 'Lobatera', 'state_id' => '20'],
            ['id' => '268', 'name' => 'Michelena', 'state_id' => '20'],
            ['id' => '269', 'name' => 'Panamericano', 'state_id' => '20'],
            ['id' => '270', 'name' => 'Pedro María Ureña', 'state_id' => '20'],
            ['id' => '271', 'name' => 'Rafael Urdaneta', 'state_id' => '20'],
            ['id' => '272', 'name' => 'Samuel Darío Maldonado', 'state_id' => '20'],
            ['id' => '273', 'name' => 'San Cristóbal', 'state_id' => '20'],
            ['id' => '274', 'name' => 'San Judas Tadeo', 'state_id' => '20'],
            ['id' => '275', 'name' => 'Seboruco', 'state_id' => '20'],
            ['id' => '276', 'name' => 'Simón Rodríguez', 'state_id' => '20'],
            ['id' => '277', 'name' => 'Sucre', 'state_id' => '20'],
            ['id' => '278', 'name' => 'Torbes', 'state_id' => '20'],
            ['id' => '279', 'name' => 'Uribante', 'state_id' => '20'],

            // ========== TRUJILLO (state_id: 21) - 20 municipios ==========
            ['id' => '280', 'name' => 'Andrés Bello', 'state_id' => '21'],
            ['id' => '281', 'name' => 'Boconó', 'state_id' => '21'],
            ['id' => '282', 'name' => 'Bolívar', 'state_id' => '21'],
            ['id' => '283', 'name' => 'Candelaria', 'state_id' => '21'],
            ['id' => '284', 'name' => 'Carache', 'state_id' => '21'],
            ['id' => '285', 'name' => 'Escuque', 'state_id' => '21'],
            ['id' => '286', 'name' => 'José Felipe Márquez Cañizales', 'state_id' => '21'],
            ['id' => '287', 'name' => 'Juan Vicente Campo Elías', 'state_id' => '21'],
            ['id' => '288', 'name' => 'La Ceiba', 'state_id' => '21'],
            ['id' => '289', 'name' => 'Miranda', 'state_id' => '21'],
            ['id' => '290', 'name' => 'Monte Carmelo', 'state_id' => '21'],
            ['id' => '291', 'name' => 'Motatán', 'state_id' => '21'],
            ['id' => '292', 'name' => 'Pampán', 'state_id' => '21'],
            ['id' => '293', 'name' => 'Pampanito', 'state_id' => '21'],
            ['id' => '294', 'name' => 'Rafael Rangel', 'state_id' => '21'],
            ['id' => '295', 'name' => 'San Rafael de Carvajal', 'state_id' => '21'],
            ['id' => '296', 'name' => 'Sucre', 'state_id' => '21'],
            ['id' => '297', 'name' => 'Trujillo', 'state_id' => '21'],
            ['id' => '298', 'name' => 'Urdaneta', 'state_id' => '21'],
            ['id' => '299', 'name' => 'Valera', 'state_id' => '21'],

            // ========== LA GUAIRA (state_id: 22) - 1 municipio ==========
            ['id' => '300', 'name' => 'Vargas', 'state_id' => '22'],

            // ========== YARACUY (state_id: 23) - 14 municipios ==========
            ['id' => '301', 'name' => 'Arístides Bastidas', 'state_id' => '23'],
            ['id' => '302', 'name' => 'Bolívar', 'state_id' => '23'],
            ['id' => '303', 'name' => 'Bruzual', 'state_id' => '23'],
            ['id' => '304', 'name' => 'Cocorote', 'state_id' => '23'],
            ['id' => '305', 'name' => 'Independencia', 'state_id' => '23'],
            ['id' => '306', 'name' => 'José Antonio Páez', 'state_id' => '23'],
            ['id' => '307', 'name' => 'La Trinidad', 'state_id' => '23'],
            ['id' => '308', 'name' => 'Manuel Monge', 'state_id' => '23'],
            ['id' => '309', 'name' => 'Nirgua', 'state_id' => '23'],
            ['id' => '310', 'name' => 'Peña', 'state_id' => '23'],
            ['id' => '311', 'name' => 'San Felipe', 'state_id' => '23'],
            ['id' => '312', 'name' => 'Sucre', 'state_id' => '23'],
            ['id' => '313', 'name' => 'Urachiche', 'state_id' => '23'],
            ['id' => '314', 'name' => 'Veroes', 'state_id' => '23'],

            // ========== ZULIA (state_id: 24) - 21 municipios ==========
            ['id' => '315', 'name' => 'Almirante Padilla', 'state_id' => '24'],
            ['id' => '316', 'name' => 'Baralt', 'state_id' => '24'],
            ['id' => '317', 'name' => 'Cabimas', 'state_id' => '24'],
            ['id' => '318', 'name' => 'Catatumbo', 'state_id' => '24'],
            ['id' => '319', 'name' => 'Colón', 'state_id' => '24'],
            ['id' => '320', 'name' => 'Francisco Javier Pulgar', 'state_id' => '24'],
            ['id' => '321', 'name' => 'Jesús Enrique Lossada', 'state_id' => '24'],
            ['id' => '322', 'name' => 'Jesús María Semprún', 'state_id' => '24'],
            ['id' => '323', 'name' => 'La Cañada de Urdaneta', 'state_id' => '24'],
            ['id' => '324', 'name' => 'Lagunillas', 'state_id' => '24'],
            ['id' => '325', 'name' => 'Machiques de Perijá', 'state_id' => '24'],
            ['id' => '326', 'name' => 'Mara', 'state_id' => '24'],
            ['id' => '327', 'name' => 'Maracaibo', 'state_id' => '24'],
            ['id' => '328', 'name' => 'Miranda', 'state_id' => '24'],
            ['id' => '329', 'name' => 'Páez', 'state_id' => '24'],
            ['id' => '330', 'name' => 'Rosario de Perijá', 'state_id' => '24'],
            ['id' => '331', 'name' => 'San Francisco', 'state_id' => '24'],
            ['id' => '332', 'name' => 'Santa Rita', 'state_id' => '24'],
            ['id' => '333', 'name' => 'Simón Bolívar', 'state_id' => '24'],
            ['id' => '334', 'name' => 'Sucre', 'state_id' => '24'],
            ['id' => '335', 'name' => 'Valmore Rodríguez', 'state_id' => '24'],
        ];

        foreach ($cities as $city) {
            City::updateOrCreate(
                ['id' => $city['id']],
                $city
            );
        }
    }
}
